import { bigint, datetime, decimal, index, int, mysqlTable, uniqueIndex, varchar } from "drizzle-orm/mysql-core"

export const stat = mysqlTable(
  "stat",
  {
    id: bigint({ mode: "number" }).autoincrement().primaryKey(),
    grain: varchar({ length: 16 }).notNull(),
    period_start: datetime({ mode: "date" }).notNull(),
    period_end: datetime({ mode: "date" }).notNull(),
    dataset: varchar({ length: 64 }).notNull().default("all"),
    tier: varchar({ length: 64 }).notNull().default("all"),
    client: varchar({ length: 64 }).notNull().default("all"),
    source: varchar({ length: 64 }).notNull().default("all"),
    provider: varchar({ length: 128 }).notNull(),
    model: varchar({ length: 256 }).notNull(),
    provider_model: varchar({ length: 256 }).notNull().default(""),
    sessions: bigint({ mode: "number" }).notNull().default(0),
    requests: bigint({ mode: "number" }).notNull().default(0),
    input_tokens: bigint({ mode: "number" }).notNull().default(0),
    output_tokens: bigint({ mode: "number" }).notNull().default(0),
    reasoning_tokens: bigint({ mode: "number" }).notNull().default(0),
    cache_read_tokens: bigint({ mode: "number" }).notNull().default(0),
    total_tokens: bigint({ mode: "number" }).notNull().default(0),
    input_cost_microcents: bigint({ mode: "number" }).notNull().default(0),
    output_cost_microcents: bigint({ mode: "number" }).notNull().default(0),
    total_cost_microcents: bigint({ mode: "number" }).notNull().default(0),
    avg_duration_ms: decimal({ precision: 12, scale: 2, mode: "number" }),
    p50_duration_ms: int(),
    p95_duration_ms: int(),
    avg_ttfb_ms: decimal({ precision: 12, scale: 2, mode: "number" }),
    p50_ttfb_ms: int(),
    p95_ttfb_ms: int(),
    avg_output_tps: decimal({ precision: 12, scale: 4, mode: "number" }),
    success_count: bigint({ mode: "number" }).notNull().default(0),
    error_count: bigint({ mode: "number" }).notNull().default(0),
    sample_count: bigint({ mode: "number" }).notNull().default(0),
    rank_by_tokens: int(),
    rank_by_requests: int(),
    rank_by_cost: int(),
    created_at: datetime({ mode: "date" }).notNull().defaultNow(),
    updated_at: datetime({ mode: "date" }).notNull().defaultNow().onUpdateNow(),
  },
  (table) => [
    uniqueIndex("uniq_model_period").on(
      table.grain,
      table.period_start,
      table.dataset,
      table.tier,
      table.client,
      table.source,
      table.provider,
      table.model,
    ),
    index("idx_leaderboard_tokens").on(table.grain, table.period_start, table.dataset, table.tier, table.total_tokens),
    index("idx_model").on(table.model, table.grain, table.period_start),
  ],
)
